import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { HStack, Flex, Text, Box, VStack, Button, Img} from '@chakra-ui/react'
import Post from '../Components/Post'
import RecommendedPost from '../Components/RecommendedPost'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'
import { useSelector, useDispatch } from 'react-redux';
import { fetchArticles, setCurrentPage } from '../features/News/NewsSlice'
import { useEffect } from 'react'
import moment from 'moment'

export default function Home() {

  const dispatch = useDispatch();
  const { articles, currentPage, status, error } = useSelector((state) => state.news);

  const num = [1,2,3,4,5]
  const nums = [1,2]

  useEffect(() => {
    dispatch(fetchArticles());
   
  }, [dispatch]);
  
  useEffect(()=>{
    console.log(articles,"articles")
  },[articles])

  // Filter articles with authors to display at the front of the page
  const filteredArticles = articles.filter((article) => article.author);

  return (
    <>
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
    <Box p ="5rem 3.5rem">
       <Flex justify="space-between">
          <Box w="50%">
             <Text fontFamily="Poppins">Innovation   2 hours ago</Text>
             <Text color="white" fontFamily="Cormorant Upright" fontSize="52px" letterSpacing="0.3%" fontWeight="bold" p="10px">
             Stay Informed, Stay Ahead: Your Gateway to Breaking News and Engaging Stories!
             </Text>
             <HStack mt="60px">
               
               {
                filteredArticles.slice(4,6).map((item)=>{
                  return(
                    <Box>
                          <Img src={item.urlToImage}  w="200px" h="100px" />
                        <Text fontWeight="700" letterSpacing="0.5%" fontSize="16px" color="#FFFFFF" p="20px 0">{item.title}</Text>
                      </Box>
                  )
                })
              }
            </HStack>
          </Box>
          <Box w="40%" p="30px" bg="rgba(255, 255, 255, 0.1)" boxShadow="rgba(0, 0, 0, 0.35) 0px 5px 15px">
            <Text 
                fontWeight="bold" 
                letterSpacing="0.5%" 
                fontSize="31px" 
                color="#FFFFFF"
                mb="20px"
                fontFamily="Poppins" 
              >Popular this week</Text>
              <VStack>
               {
                filteredArticles.slice(0,3).map((item)=>{
                  return(
                    <HStack align="flex-start" >
                    
                        <Img src={item.urlToImage}  w="200px" h="100px" />
                    
                        <Box>
                             <HStack>
                                <Text fontWeight="bold" letterSpacing="0.8%" fontSize="16px" fontFamily="Poppins"  color="#FFFFFF">{item.author || 'Random'} 
                                </Text>
                                <Text fontWeight="bold" letterSpacing="0.8%" fontSize="10px" fontFamily="Poppins"  color="#FFFFFF">{moment(item.publishedAt).startOf('day').fromNow()}</Text>
                             </HStack>
                            <Text fontWeight="700" letterSpacing="0.5%" fontSize="16px" color="#FFFFFF" p="20px 0" fontFamily="Cormorant Upright" >{item.title}</Text>
                        </Box>
                    </HStack>
                  )
                })
              }
               </VStack>
          </Box>
       </Flex>
    </Box>
  </div>
  <Post text="Our Latest Post"></Post>
  <RecommendedPost></RecommendedPost>
  <Footer></Footer>
  </>
  )
}
