import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { HStack, Flex, Text, Box, VStack, Button} from '@chakra-ui/react'
import Post from '../Components/Post'
import RecommendedPost from '../Components/RecommendedPost'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'

export default function Home() {


  const num = [1,2,3,4,5]
  const nums = [1,2]

  return (
    <>
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
    <Box p ="5rem 3.5rem">
       <Flex justify="space-between">
          <Box w="50%">
             <Text fontFamily="Poppins">Innovation   2 hours ago</Text>
             <Text color="white" fontFamily="Cormorant Upright" fontSize="52px" letterSpacing="0.3%" fontWeight="bold" p="10px">
               Charge Two Devices at the Same Time With This Magnetic Wireless Charging Dock
             </Text>
             <HStack mt="60px">
               <Box>
                 <Box w="200px" h="100px" bg="#F2F2F2"></Box>
                    <Text fontWeight="700" letterSpacing="0.5%" fontSize="16px" color="#FFFFFF" p="20px 0">7 Ways You Can Reduce Climate Change</Text>
               </Box>
               <Box>
                 <Box w="200px" h="100px" bg="#F2F2F2"></Box>
                    <Text fontWeight="700" letterSpacing="0.5%" fontSize="16px" color="#FFFFFF" p="20px 0">7 Ways You Can Reduce Climate Change</Text>
               </Box>
            </HStack>
          </Box>
          <Box w="40%" p="30px" bg="rgba(255, 255, 255, 0.1)" boxShadow="rgba(0, 0, 0, 0.35) 0px 5px 15px">
            <Text 
                fontWeight="bold" 
                letterSpacing="0.5%" 
                fontSize="31px" 
                color="#FFFFFF"
                mb="20px"
                fontFamily="Poppins" 
              >Popular this week</Text>
              <VStack>
               {
                num.map((item)=>{
                  return(
                    <HStack align="flex-start">
                      <Box w="200px" h="100px" bg="#F2F2F2"></Box>
                        <Box>
                          <Text fontWeight="bold" letterSpacing="0.8%" fontSize="12px" fontFamily="Poppins"  color="#FFFFFF">Innovation 2 Hours ago</Text>
                            <Text fontWeight="700" letterSpacing="0.5%" fontSize="16px" color="#FFFFFF" p="20px 0" fontFamily="Cormorant Upright" >7 Ways You Can Reduce Climate Change</Text>
                        </Box>
                    </HStack>
                  )
                })
              }
               </VStack>
          </Box>
       </Flex>
    </Box>
  </div>
  <Post text="Our Latest Post"></Post>
  <RecommendedPost></RecommendedPost>
  <Footer></Footer>
  </>
  )
}
